# Generated by Django 4.2.24 on 2025-09-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='dish',
            unique_together={('name', 'menu_type', 'category', 'subcategory')},
        ),
    ]
