# Generated by Django 4.2.24 on 2025-09-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_dish_options_alter_dish_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.URLField(blank=True, default='https://i.ibb.co/7QpKsCX/white-background.jpg'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.URLField(blank=True, default='https://i.ibb.co/7QpKsCX/white-background.jpg'),
        ),
        migrations.AlterField(
            model_name='menu_type',
            name='background_image',
            field=models.URLField(blank=True, default='https://i.ibb.co/7QpKsCX/white-background.jpg'),
        ),
        migrations.AlterField(
            model_name='menu_type',
            name='logo',
            field=models.URLField(blank=True, default='https://i.ibb.co/7QpKsCX/white-background.jpg'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcat_image',
            field=models.URLField(blank=True, default='https://i.ibb.co/7QpKsCX/white-background.jpg'),
        ),
    ]
